defmodule ItohTsujiiTest do
  use ExUnit.Case

  @tag :gen_test_mul_inv2
  test "GF(2, 1) itoh tsujii" do
    gf = GF.new(2, 1, [1,1])
    assert 1 == GF.Algorithms.itoh_tsujii(gf, 1)
  end

  @tag :gen_test_mul_inv2
  test "GF(2, 2) itoh tsujii" do
    gf = GF.new(2, 2, [1,1,1])
    assert 1 == GF.Algorithms.itoh_tsujii(gf, 1)
    assert 3 == GF.Algorithms.itoh_tsujii(gf, 2)
    assert 2 == GF.Algorithms.itoh_tsujii(gf, 3)
  end

  @tag :gen_test_mul_inv
  test "GF(2, 3) itoh tsujii" do
    gf = GF.new(2, 3, [1,1,0,1])
    assert 1 == GF.Algorithms.itoh_tsujii(gf, 1)
    assert 5 == GF.Algorithms.itoh_tsujii(gf, 2)
    assert 6 == GF.Algorithms.itoh_tsujii(gf, 3)
    assert 7 == GF.Algorithms.itoh_tsujii(gf, 4)
    assert 2 == GF.Algorithms.itoh_tsujii(gf, 5)
    assert 3 == GF.Algorithms.itoh_tsujii(gf, 6)
    assert 4 == GF.Algorithms.itoh_tsujii(gf, 7)
  end

  @tag :gen_test_mul_inv2
  test "GF(3, 1) itoh tsujii" do
    gf = GF.new(3, 1, [1,1])
    assert 1 == GF.Algorithms.itoh_tsujii(gf, 1)
    assert 2 == GF.Algorithms.itoh_tsujii(gf, 2)
  end

  @tag :gen_test_mul_inv2
  test "GF(3, 2) itoh tsujii" do
    gf = GF.new(3, 2, [2,2,1])
    assert 1 == GF.Algorithms.itoh_tsujii(gf, 1)
    assert 2 == GF.Algorithms.itoh_tsujii(gf, 2)
    assert 5 == GF.Algorithms.itoh_tsujii(gf, 3)
    assert 8 == GF.Algorithms.itoh_tsujii(gf, 4)
    assert 3 == GF.Algorithms.itoh_tsujii(gf, 5)
    assert 7 == GF.Algorithms.itoh_tsujii(gf, 6)
    assert 6 == GF.Algorithms.itoh_tsujii(gf, 7)
    assert 4 == GF.Algorithms.itoh_tsujii(gf, 8)
  end

  @tag :gen_test_mul_inv2
  test "GF(3, 3) itoh tsujii" do
    gf = GF.new(3, 3, [1,2,0,1])
    assert 1 == GF.Algorithms.itoh_tsujii(gf, 1)
    assert 2 == GF.Algorithms.itoh_tsujii(gf, 2)
    assert 19 == GF.Algorithms.itoh_tsujii(gf, 3)
    assert 21 == GF.Algorithms.itoh_tsujii(gf, 4)
    assert 24 == GF.Algorithms.itoh_tsujii(gf, 5)
    assert 11 == GF.Algorithms.itoh_tsujii(gf, 6)
    assert 12 == GF.Algorithms.itoh_tsujii(gf, 7)
    assert 15 == GF.Algorithms.itoh_tsujii(gf, 8)
    assert 25 == GF.Algorithms.itoh_tsujii(gf, 9)
    assert 23 == GF.Algorithms.itoh_tsujii(gf, 10)
    assert 6 == GF.Algorithms.itoh_tsujii(gf, 11)
    assert 7 == GF.Algorithms.itoh_tsujii(gf, 12)
    assert 22 == GF.Algorithms.itoh_tsujii(gf, 13)
    assert 18 == GF.Algorithms.itoh_tsujii(gf, 14)
    assert 8 == GF.Algorithms.itoh_tsujii(gf, 15)
    assert 20 == GF.Algorithms.itoh_tsujii(gf, 16)
    assert 26 == GF.Algorithms.itoh_tsujii(gf, 17)
    assert 14 == GF.Algorithms.itoh_tsujii(gf, 18)
    assert 3 == GF.Algorithms.itoh_tsujii(gf, 19)
    assert 16 == GF.Algorithms.itoh_tsujii(gf, 20)
    assert 4 == GF.Algorithms.itoh_tsujii(gf, 21)
    assert 13 == GF.Algorithms.itoh_tsujii(gf, 22)
    assert 10 == GF.Algorithms.itoh_tsujii(gf, 23)
    assert 5 == GF.Algorithms.itoh_tsujii(gf, 24)
    assert 9 == GF.Algorithms.itoh_tsujii(gf, 25)
    assert 17 == GF.Algorithms.itoh_tsujii(gf, 26)
  end

  @tag :gen_test_mul_inv2
  test "GF(5, 1) itoh tsujii" do
    gf = GF.new(5, 1, [3,1])
    assert 1 == GF.Algorithms.itoh_tsujii(gf, 1)
    assert 3 == GF.Algorithms.itoh_tsujii(gf, 2)
    assert 2 == GF.Algorithms.itoh_tsujii(gf, 3)
    assert 4 == GF.Algorithms.itoh_tsujii(gf, 4)
  end

  @tag :gen_test_mul_inv2
  test "GF(5, 2) itoh tsujii" do
    gf = GF.new(5, 2, [2,4,1])
    assert 1 == GF.Algorithms.itoh_tsujii(gf, 1)
    assert 3 == GF.Algorithms.itoh_tsujii(gf, 2)
    assert 2 == GF.Algorithms.itoh_tsujii(gf, 3)
    assert 4 == GF.Algorithms.itoh_tsujii(gf, 4)
    assert 13 == GF.Algorithms.itoh_tsujii(gf, 5)
    assert 8 == GF.Algorithms.itoh_tsujii(gf, 6)
    assert 16 == GF.Algorithms.itoh_tsujii(gf, 7)
    assert 6 == GF.Algorithms.itoh_tsujii(gf, 8)
    assert 10 == GF.Algorithms.itoh_tsujii(gf, 9)
    assert 9 == GF.Algorithms.itoh_tsujii(gf, 10)
    assert 18 == GF.Algorithms.itoh_tsujii(gf, 11)
    assert 19 == GF.Algorithms.itoh_tsujii(gf, 12)
    assert 5 == GF.Algorithms.itoh_tsujii(gf, 13)
    assert 23 == GF.Algorithms.itoh_tsujii(gf, 14)
    assert 21 == GF.Algorithms.itoh_tsujii(gf, 15)
    assert 7 == GF.Algorithms.itoh_tsujii(gf, 16)
    assert 20 == GF.Algorithms.itoh_tsujii(gf, 17)
    assert 11 == GF.Algorithms.itoh_tsujii(gf, 18)
    assert 12 == GF.Algorithms.itoh_tsujii(gf, 19)
    assert 17 == GF.Algorithms.itoh_tsujii(gf, 20)
    assert 15 == GF.Algorithms.itoh_tsujii(gf, 21)
    assert 24 == GF.Algorithms.itoh_tsujii(gf, 22)
    assert 14 == GF.Algorithms.itoh_tsujii(gf, 23)
    assert 22 == GF.Algorithms.itoh_tsujii(gf, 24)
  end

  @tag :gen_test_mul_inv2
  test "GF(5, 3) itoh tsujii" do
    gf = GF.new(5, 3, [3,3,0,1])
    assert 1 == GF.Algorithms.itoh_tsujii(gf, 1)
    assert 3 == GF.Algorithms.itoh_tsujii(gf, 2)
    assert 4 == GF.Algorithms.itoh_tsujii(gf, 4)
    assert 49 == GF.Algorithms.itoh_tsujii(gf, 6)
    assert 49 == GF.Algorithms.itoh_tsujii(gf, 6)
    assert 63 == GF.Algorithms.itoh_tsujii(gf, 9)
    assert 37 == GF.Algorithms.itoh_tsujii(gf, 11)
    assert 37 == GF.Algorithms.itoh_tsujii(gf, 11)
    assert 37 == GF.Algorithms.itoh_tsujii(gf, 11)
    assert 37 == GF.Algorithms.itoh_tsujii(gf, 11)
    assert 87 == GF.Algorithms.itoh_tsujii(gf, 12)
    assert 34 == GF.Algorithms.itoh_tsujii(gf, 13)
    assert 96 == GF.Algorithms.itoh_tsujii(gf, 14)
    assert 59 == GF.Algorithms.itoh_tsujii(gf, 16)
    assert 51 == GF.Algorithms.itoh_tsujii(gf, 20)
    assert 92 == GF.Algorithms.itoh_tsujii(gf, 21)
    assert 81 == GF.Algorithms.itoh_tsujii(gf, 22)
    assert 81 == GF.Algorithms.itoh_tsujii(gf, 22)
    assert 123 == GF.Algorithms.itoh_tsujii(gf, 26)
    assert 15 == GF.Algorithms.itoh_tsujii(gf, 28)
    assert 15 == GF.Algorithms.itoh_tsujii(gf, 28)
    assert 55 == GF.Algorithms.itoh_tsujii(gf, 30)
    assert 35 == GF.Algorithms.itoh_tsujii(gf, 31)
    assert 104 == GF.Algorithms.itoh_tsujii(gf, 32)
    assert 104 == GF.Algorithms.itoh_tsujii(gf, 32)
    assert 13 == GF.Algorithms.itoh_tsujii(gf, 34)
    assert 27 == GF.Algorithms.itoh_tsujii(gf, 36)
    assert 11 == GF.Algorithms.itoh_tsujii(gf, 37)
    assert 99 == GF.Algorithms.itoh_tsujii(gf, 39)
    assert 105 == GF.Algorithms.itoh_tsujii(gf, 41)
    assert 105 == GF.Algorithms.itoh_tsujii(gf, 41)
    assert 105 == GF.Algorithms.itoh_tsujii(gf, 41)
    assert 105 == GF.Algorithms.itoh_tsujii(gf, 41)
    assert 82 == GF.Algorithms.itoh_tsujii(gf, 43)
    assert 77 == GF.Algorithms.itoh_tsujii(gf, 44)
    assert 114 == GF.Algorithms.itoh_tsujii(gf, 45)
    assert 114 == GF.Algorithms.itoh_tsujii(gf, 45)
    assert 61 == GF.Algorithms.itoh_tsujii(gf, 46)
    assert 61 == GF.Algorithms.itoh_tsujii(gf, 46)
    assert 50 == GF.Algorithms.itoh_tsujii(gf, 48)
    assert 20 == GF.Algorithms.itoh_tsujii(gf, 51)
    assert 64 == GF.Algorithms.itoh_tsujii(gf, 52)
    assert 111 == GF.Algorithms.itoh_tsujii(gf, 53)
    assert 83 == GF.Algorithms.itoh_tsujii(gf, 54)
    assert 30 == GF.Algorithms.itoh_tsujii(gf, 55)
    assert 30 == GF.Algorithms.itoh_tsujii(gf, 55)
    assert 30 == GF.Algorithms.itoh_tsujii(gf, 55)
    assert 116 == GF.Algorithms.itoh_tsujii(gf, 56)
    assert 65 == GF.Algorithms.itoh_tsujii(gf, 57)
    assert 101 == GF.Algorithms.itoh_tsujii(gf, 58)
    assert 101 == GF.Algorithms.itoh_tsujii(gf, 58)
    assert 16 == GF.Algorithms.itoh_tsujii(gf, 59)
    assert 16 == GF.Algorithms.itoh_tsujii(gf, 59)
    assert 16 == GF.Algorithms.itoh_tsujii(gf, 59)
    assert 40 == GF.Algorithms.itoh_tsujii(gf, 60)
    assert 40 == GF.Algorithms.itoh_tsujii(gf, 60)
    assert 40 == GF.Algorithms.itoh_tsujii(gf, 60)
    assert 80 == GF.Algorithms.itoh_tsujii(gf, 62)
    assert 9 == GF.Algorithms.itoh_tsujii(gf, 63)
    assert 9 == GF.Algorithms.itoh_tsujii(gf, 63)
    assert 25 == GF.Algorithms.itoh_tsujii(gf, 66)
    assert 25 == GF.Algorithms.itoh_tsujii(gf, 66)
    assert 38 == GF.Algorithms.itoh_tsujii(gf, 69)
    assert 47 == GF.Algorithms.itoh_tsujii(gf, 71)
    assert 47 == GF.Algorithms.itoh_tsujii(gf, 71)
    assert 112 == GF.Algorithms.itoh_tsujii(gf, 73)
    assert 112 == GF.Algorithms.itoh_tsujii(gf, 73)
    assert 107 == GF.Algorithms.itoh_tsujii(gf, 75)
    assert 107 == GF.Algorithms.itoh_tsujii(gf, 75)
    assert 107 == GF.Algorithms.itoh_tsujii(gf, 75)
    assert 44 == GF.Algorithms.itoh_tsujii(gf, 77)
    assert 91 == GF.Algorithms.itoh_tsujii(gf, 78)
    assert 91 == GF.Algorithms.itoh_tsujii(gf, 78)
    assert 5 == GF.Algorithms.itoh_tsujii(gf, 79)
    assert 62 == GF.Algorithms.itoh_tsujii(gf, 80)
    assert 78 == GF.Algorithms.itoh_tsujii(gf, 91)
    assert 21 == GF.Algorithms.itoh_tsujii(gf, 92)
    assert 109 == GF.Algorithms.itoh_tsujii(gf, 94)
    assert 14 == GF.Algorithms.itoh_tsujii(gf, 96)
    assert 85 == GF.Algorithms.itoh_tsujii(gf, 98)
    assert 85 == GF.Algorithms.itoh_tsujii(gf, 98)
    assert 39 == GF.Algorithms.itoh_tsujii(gf, 99)
    assert 39 == GF.Algorithms.itoh_tsujii(gf, 99)
    assert 39 == GF.Algorithms.itoh_tsujii(gf, 99)
    assert 89 == GF.Algorithms.itoh_tsujii(gf, 100)
    assert 58 == GF.Algorithms.itoh_tsujii(gf, 101)
    assert 58 == GF.Algorithms.itoh_tsujii(gf, 101)
    assert 32 == GF.Algorithms.itoh_tsujii(gf, 104)
    assert 32 == GF.Algorithms.itoh_tsujii(gf, 104)
    assert 24 == GF.Algorithms.itoh_tsujii(gf, 106)
    assert 24 == GF.Algorithms.itoh_tsujii(gf, 106)
    assert 90 == GF.Algorithms.itoh_tsujii(gf, 110)
    assert 53 == GF.Algorithms.itoh_tsujii(gf, 111)
    assert 73 == GF.Algorithms.itoh_tsujii(gf, 112)
    assert 124 == GF.Algorithms.itoh_tsujii(gf, 115)
    assert 124 == GF.Algorithms.itoh_tsujii(gf, 115)
    assert 19 == GF.Algorithms.itoh_tsujii(gf, 118)
    assert 103 == GF.Algorithms.itoh_tsujii(gf, 119)
    assert 95 == GF.Algorithms.itoh_tsujii(gf, 120)
    assert 26 == GF.Algorithms.itoh_tsujii(gf, 123)
  end

  @tag :gen_test_mul_inv2
  test "GF(7, 1) itoh tsujii" do
    gf = GF.new(7, 1, [4,1])
    assert 1 == GF.Algorithms.itoh_tsujii(gf, 1)
    assert 4 == GF.Algorithms.itoh_tsujii(gf, 2)
    assert 5 == GF.Algorithms.itoh_tsujii(gf, 3)
    assert 2 == GF.Algorithms.itoh_tsujii(gf, 4)
    assert 3 == GF.Algorithms.itoh_tsujii(gf, 5)
    assert 6 == GF.Algorithms.itoh_tsujii(gf, 6)
  end

  @tag :gen_test_mul_inv2
  test "GF(7, 2) itoh tsujii" do
    gf = GF.new(7, 2, [3,6,1])
    assert 1 == GF.Algorithms.itoh_tsujii(gf, 1)
    assert 4 == GF.Algorithms.itoh_tsujii(gf, 2)
    assert 5 == GF.Algorithms.itoh_tsujii(gf, 3)
    assert 2 == GF.Algorithms.itoh_tsujii(gf, 4)
    assert 3 == GF.Algorithms.itoh_tsujii(gf, 5)
    assert 6 == GF.Algorithms.itoh_tsujii(gf, 6)
    assert 19 == GF.Algorithms.itoh_tsujii(gf, 7)
    assert 34 == GF.Algorithms.itoh_tsujii(gf, 8)
    assert 26 == GF.Algorithms.itoh_tsujii(gf, 9)
    assert 46 == GF.Algorithms.itoh_tsujii(gf, 10)
    assert 27 == GF.Algorithms.itoh_tsujii(gf, 11)
    assert 32 == GF.Algorithms.itoh_tsujii(gf, 12)
    assert 14 == GF.Algorithms.itoh_tsujii(gf, 13)
    assert 13 == GF.Algorithms.itoh_tsujii(gf, 14)
    assert 38 == GF.Algorithms.itoh_tsujii(gf, 15)
    assert 17 == GF.Algorithms.itoh_tsujii(gf, 16)
    assert 16 == GF.Algorithms.itoh_tsujii(gf, 17)
    assert 41 == GF.Algorithms.itoh_tsujii(gf, 18)
    assert 7 == GF.Algorithms.itoh_tsujii(gf, 19)
    assert 23 == GF.Algorithms.itoh_tsujii(gf, 20)
    assert 25 == GF.Algorithms.itoh_tsujii(gf, 21)
    assert 48 == GF.Algorithms.itoh_tsujii(gf, 22)
    assert 20 == GF.Algorithms.itoh_tsujii(gf, 23)
    assert 44 == GF.Algorithms.itoh_tsujii(gf, 24)
    assert 21 == GF.Algorithms.itoh_tsujii(gf, 25)
    assert 9 == GF.Algorithms.itoh_tsujii(gf, 26)
    assert 11 == GF.Algorithms.itoh_tsujii(gf, 27)
    assert 31 == GF.Algorithms.itoh_tsujii(gf, 28)
    assert 45 == GF.Algorithms.itoh_tsujii(gf, 29)
    assert 47 == GF.Algorithms.itoh_tsujii(gf, 30)
    assert 28 == GF.Algorithms.itoh_tsujii(gf, 31)
    assert 12 == GF.Algorithms.itoh_tsujii(gf, 32)
    assert 36 == GF.Algorithms.itoh_tsujii(gf, 33)
    assert 8 == GF.Algorithms.itoh_tsujii(gf, 34)
    assert 43 == GF.Algorithms.itoh_tsujii(gf, 35)
    assert 33 == GF.Algorithms.itoh_tsujii(gf, 36)
    assert 42 == GF.Algorithms.itoh_tsujii(gf, 37)
    assert 15 == GF.Algorithms.itoh_tsujii(gf, 38)
    assert 40 == GF.Algorithms.itoh_tsujii(gf, 39)
    assert 39 == GF.Algorithms.itoh_tsujii(gf, 40)
    assert 18 == GF.Algorithms.itoh_tsujii(gf, 41)
    assert 37 == GF.Algorithms.itoh_tsujii(gf, 42)
    assert 35 == GF.Algorithms.itoh_tsujii(gf, 43)
    assert 24 == GF.Algorithms.itoh_tsujii(gf, 44)
    assert 29 == GF.Algorithms.itoh_tsujii(gf, 45)
    assert 10 == GF.Algorithms.itoh_tsujii(gf, 46)
    assert 30 == GF.Algorithms.itoh_tsujii(gf, 47)
    assert 22 == GF.Algorithms.itoh_tsujii(gf, 48)
  end

  @tag :gen_test_mul_inv2
  test "GF(7, 3) itoh tsujii" do
    gf = GF.new(7, 3, [4,0,6,1])
    assert 1 == GF.Algorithms.itoh_tsujii(gf, 1)
    assert 330 == GF.Algorithms.itoh_tsujii(gf, 11)
    assert 330 == GF.Algorithms.itoh_tsujii(gf, 11)
    assert 341 == GF.Algorithms.itoh_tsujii(gf, 12)
    assert 174 == GF.Algorithms.itoh_tsujii(gf, 17)
    assert 116 == GF.Algorithms.itoh_tsujii(gf, 22)
    assert 162 == GF.Algorithms.itoh_tsujii(gf, 23)
    assert 289 == GF.Algorithms.itoh_tsujii(gf, 27)
    assert 175 == GF.Algorithms.itoh_tsujii(gf, 28)
    assert 133 == GF.Algorithms.itoh_tsujii(gf, 42)
    assert 69 == GF.Algorithms.itoh_tsujii(gf, 45)
    assert 316 == GF.Algorithms.itoh_tsujii(gf, 47)
    assert 239 == GF.Algorithms.itoh_tsujii(gf, 48)
    assert 214 == GF.Algorithms.itoh_tsujii(gf, 50)
    assert 180 == GF.Algorithms.itoh_tsujii(gf, 52)
    assert 179 == GF.Algorithms.itoh_tsujii(gf, 64)
    assert 96 == GF.Algorithms.itoh_tsujii(gf, 79)
    assert 208 == GF.Algorithms.itoh_tsujii(gf, 80)
    assert 9 == GF.Algorithms.itoh_tsujii(gf, 83)
    assert 9 == GF.Algorithms.itoh_tsujii(gf, 83)
    assert 236 == GF.Algorithms.itoh_tsujii(gf, 85)
    assert 339 == GF.Algorithms.itoh_tsujii(gf, 89)
    assert 332 == GF.Algorithms.itoh_tsujii(gf, 90)
    assert 35 == GF.Algorithms.itoh_tsujii(gf, 91)
    assert 274 == GF.Algorithms.itoh_tsujii(gf, 101)
    assert 274 == GF.Algorithms.itoh_tsujii(gf, 101)
    assert 297 == GF.Algorithms.itoh_tsujii(gf, 114)
    assert 249 == GF.Algorithms.itoh_tsujii(gf, 125)
    assert 158 == GF.Algorithms.itoh_tsujii(gf, 127)
    assert 261 == GF.Algorithms.itoh_tsujii(gf, 128)
    assert 26 == GF.Algorithms.itoh_tsujii(gf, 131)
    assert 211 == GF.Algorithms.itoh_tsujii(gf, 136)
    assert 271 == GF.Algorithms.itoh_tsujii(gf, 138)
    assert 10 == GF.Algorithms.itoh_tsujii(gf, 143)
    assert 221 == GF.Algorithms.itoh_tsujii(gf, 145)
    assert 121 == GF.Algorithms.itoh_tsujii(gf, 146)
    assert 130 == GF.Algorithms.itoh_tsujii(gf, 153)
    assert 127 == GF.Algorithms.itoh_tsujii(gf, 158)
    assert 210 == GF.Algorithms.itoh_tsujii(gf, 164)
    assert 247 == GF.Algorithms.itoh_tsujii(gf, 166)
    assert 189 == GF.Algorithms.itoh_tsujii(gf, 167)
    assert 137 == GF.Algorithms.itoh_tsujii(gf, 169)
    assert 252 == GF.Algorithms.itoh_tsujii(gf, 172)
    assert 17 == GF.Algorithms.itoh_tsujii(gf, 174)
    assert 64 == GF.Algorithms.itoh_tsujii(gf, 179)
    assert 115 == GF.Algorithms.itoh_tsujii(gf, 181)
    assert 235 == GF.Algorithms.itoh_tsujii(gf, 182)
    assert 308 == GF.Algorithms.itoh_tsujii(gf, 183)
    assert 167 == GF.Algorithms.itoh_tsujii(gf, 189)
    assert 97 == GF.Algorithms.itoh_tsujii(gf, 192)
    assert 15 == GF.Algorithms.itoh_tsujii(gf, 193)
    assert 102 == GF.Algorithms.itoh_tsujii(gf, 195)
    assert 25 == GF.Algorithms.itoh_tsujii(gf, 196)
    assert 269 == GF.Algorithms.itoh_tsujii(gf, 197)
    assert 78 == GF.Algorithms.itoh_tsujii(gf, 200)
    assert 78 == GF.Algorithms.itoh_tsujii(gf, 200)
    assert 41 == GF.Algorithms.itoh_tsujii(gf, 206)
    assert 41 == GF.Algorithms.itoh_tsujii(gf, 206)
    assert 302 == GF.Algorithms.itoh_tsujii(gf, 207)
    assert 18 == GF.Algorithms.itoh_tsujii(gf, 213)
    assert 50 == GF.Algorithms.itoh_tsujii(gf, 214)
    assert 84 == GF.Algorithms.itoh_tsujii(gf, 216)
    assert 109 == GF.Algorithms.itoh_tsujii(gf, 223)
    assert 39 == GF.Algorithms.itoh_tsujii(gf, 225)
    assert 277 == GF.Algorithms.itoh_tsujii(gf, 226)
    assert 203 == GF.Algorithms.itoh_tsujii(gf, 232)
    assert 103 == GF.Algorithms.itoh_tsujii(gf, 233)
    assert 48 == GF.Algorithms.itoh_tsujii(gf, 239)
    assert 272 == GF.Algorithms.itoh_tsujii(gf, 241)
    assert 296 == GF.Algorithms.itoh_tsujii(gf, 243)
    assert 286 == GF.Algorithms.itoh_tsujii(gf, 244)
    assert 134 == GF.Algorithms.itoh_tsujii(gf, 246)
    assert 134 == GF.Algorithms.itoh_tsujii(gf, 246)
    assert 166 == GF.Algorithms.itoh_tsujii(gf, 247)
    assert 292 == GF.Algorithms.itoh_tsujii(gf, 250)
    assert 329 == GF.Algorithms.itoh_tsujii(gf, 255)
    assert 77 == GF.Algorithms.itoh_tsujii(gf, 257)
    assert 240 == GF.Algorithms.itoh_tsujii(gf, 260)
    assert 128 == GF.Algorithms.itoh_tsujii(gf, 261)
    assert 165 == GF.Algorithms.itoh_tsujii(gf, 264)
    assert 229 == GF.Algorithms.itoh_tsujii(gf, 270)
    assert 205 == GF.Algorithms.itoh_tsujii(gf, 275)
    assert 16 == GF.Algorithms.itoh_tsujii(gf, 276)
    assert 16 == GF.Algorithms.itoh_tsujii(gf, 276)
    assert 226 == GF.Algorithms.itoh_tsujii(gf, 277)
    assert 209 == GF.Algorithms.itoh_tsujii(gf, 281)
    assert 34 == GF.Algorithms.itoh_tsujii(gf, 283)
    assert 267 == GF.Algorithms.itoh_tsujii(gf, 288)
    assert 219 == GF.Algorithms.itoh_tsujii(gf, 298)
    assert 65 == GF.Algorithms.itoh_tsujii(gf, 299)
    assert 320 == GF.Algorithms.itoh_tsujii(gf, 303)
    assert 88 == GF.Algorithms.itoh_tsujii(gf, 305)
    assert 323 == GF.Algorithms.itoh_tsujii(gf, 307)
    assert 202 == GF.Algorithms.itoh_tsujii(gf, 312)
    assert 163 == GF.Algorithms.itoh_tsujii(gf, 314)
    assert 142 == GF.Algorithms.itoh_tsujii(gf, 315)
    assert 150 == GF.Algorithms.itoh_tsujii(gf, 321)
    assert 11 == GF.Algorithms.itoh_tsujii(gf, 330)
    assert 11 == GF.Algorithms.itoh_tsujii(gf, 330)
    assert 293 == GF.Algorithms.itoh_tsujii(gf, 336)
  end
end
